package com.mygdx.game.Persistance.Relations;

import com.mygdx.game.Persistance.AppDatabase;
import com.mygdx.game.Persistance.PersistenceClient;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import static org.junit.Assert.assertTrue;


/*
 * Class currently serves only as autogenerated class.
 * If any class specific logic will be made, the logic will be tested here.
 */
@RunWith(AndroidJUnit4.class)
public class NNVideoFrameDAOTest {
    private AppDatabase  appDatabase;
    @Before
    public void createDb() {
        this.appDatabase = PersistenceClient.getInstance(ApplicationProvider.getApplicationContext(), "debugDB").getAppDatabase();
        this.appDatabase.clearAllTables();
    }

    @After
    public void closeDb() {
        this.appDatabase.close();
    }

    @Test
    public void exampleTest() {
        assertTrue(true);
    }

}



